const images = {
  bannerSrc: require('../assets/banner.jpg'),
  logoSrc: require('../assets/logo.png'),
  siteLogo: require('../assets/umgc-logo.svg'),
  noNotification: require('../assets/no_notif.svg'),
  artistBg: require('../assets/artists.jpg'),
  brandBg: require('../assets/brands_and_labels.jpg'),
  systemBg: require('../assets/systems_and_applications.jpg'),
  defaultAvatar: require('../assets/avatar.svg'),
  placeholder: require('../assets/placeholder.jpg'),
  add: require('../assets/add.svg'),
  faceBrowser: require('../assets/face_browser.svg'),
  faceDocument: require('../assets/face_document.svg'),
  faceHeart: require('../assets/face_heart.svg'),
  faceLock: require('../assets/face_lock.svg'),
  faceStop: require('../assets/face_stop.svg'),
  chromeIcon: require('../assets/Chrome-Logo-Icon.png'),
  safariIcon: require('../assets/Safari_logo.png'),
  edgeIcon: require('../assets/Microsoft-Edge.png'),
  external: require('../assets/external.svg'),
  allLinksGrid: require('../assets/all_links_grid.svg'),
  gearIcon: require('../assets/gear.svg'),
  defaultIcon: require('../assets/default_icon.svg'),
  remove: require('../assets/remove.svg'),
  defaultIconCircle: require('../assets/default_icon_circle.svg'),
  spinner: require('../assets/spinner.gif'),
  caretRight: require('../assets/caret-right.svg'),
  caretLeft: require('../assets/caret-left.svg'),
  appreciationCardSampleTop: require('../assets/ap-text.svg'),
  appreciationCardSampleBottom: require('../assets/man-guitar.svg'),
  removeFilter: require('../assets/times-circle.svg')
};

export default images;
